import { StyleSheet } from 'react-native';

import { COLORS, TOP_BAR_OFFSET, ZOOM_BAR_WIDTH } from '../config/camera';

export const styles = StyleSheet.create({
  safeArea: { flex: 1, backgroundColor: COLORS.bg },
  root: { flex: 1, backgroundColor: COLORS.bg },
  previewArea: { position: 'absolute', left: 0, right: 0, top: 0, bottom: 0, overflow: 'hidden', backgroundColor: '#05070a' },
  focusLayer: { position: 'absolute', top: 0, right: 0, bottom: 0, left: 0, zIndex: 8 },
  centerScreen: { flex: 1, alignItems: 'center', justifyContent: 'center', padding: 28, backgroundColor: COLORS.bg },
  title: { color: COLORS.text, fontSize: 24, fontWeight: '800', marginBottom: 12 },
  description: { color: COLORS.muted, fontSize: 14, lineHeight: 22, textAlign: 'center', marginBottom: 20 },
  primaryButton: { borderRadius: 999, backgroundColor: COLORS.text, paddingHorizontal: 22, paddingVertical: 12 },
  primaryButtonText: { color: '#000', fontWeight: '800' },
  previewStatus: { position: 'absolute', left: 22, right: 22, top: '40%', zIndex: 12, padding: 14, borderRadius: 18, backgroundColor: 'rgba(0,0,0,0.62)', borderWidth: 1, borderColor: COLORS.line },
  previewStatusTitle: { color: COLORS.text, fontSize: 15, fontWeight: '900', marginBottom: 6, textAlign: 'center' },
  previewStatusText: { color: COLORS.muted, fontSize: 12, lineHeight: 18, textAlign: 'center' },
  mainPreviewCenter: { position: 'absolute', left: 0, right: 0, alignItems: 'center', justifyContent: 'center', backgroundColor: '#000' },
  mainContainedSlot: { backgroundColor: '#000', overflow: 'hidden' },
  mainPortraitSlot: { height: '100%', aspectRatio: 3 / 4, backgroundColor: '#000', overflow: 'hidden' },
  mainFullSlot: { width: '100%', height: '100%' },
  mainLandscapeSlot: { width: '100%', aspectRatio: 16 / 9, backgroundColor: '#000', overflow: 'hidden' },
  mainTallLandscapeSlot: { height: '100%', aspectRatio: 16 / 9, backgroundColor: '#000', overflow: 'hidden' },
  topBar: { position: 'absolute', left: 0, right: 0, top: TOP_BAR_OFFSET, zIndex: 20, paddingHorizontal: 8, paddingVertical: 8, flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between' },
  topSide: { width: 88, height: 42 },
  topCenter: { position: 'absolute', left: 88, right: 88, alignItems: 'center', justifyContent: 'center' },
  topActions: { flexDirection: 'row', gap: 6, alignItems: 'center' },
  aspectRow: { maxWidth: '100%', flexDirection: 'row', alignItems: 'center', justifyContent: 'center', gap: 2, padding: 4, borderRadius: 20, backgroundColor: 'rgba(0,0,0,0.42)' },
  aspectButton: { minWidth: 34, height: 30, borderRadius: 15, alignItems: 'center', justifyContent: 'center', paddingHorizontal: 5 },
  aspectButtonActive: { backgroundColor: 'rgba(255,209,102,0.22)' },
  aspectText: { color: COLORS.muted, fontSize: 11, fontWeight: '900' },
  aspectTextActive: { color: COLORS.text },
  topVideoControls: { alignItems: 'center', justifyContent: 'center', gap: 6 },
  topVideoPills: { flexDirection: 'row', alignItems: 'center', justifyContent: 'center', gap: 8 },
  topPill: { minWidth: 58, height: 34, borderRadius: 17, alignItems: 'center', justifyContent: 'center', paddingHorizontal: 10, backgroundColor: 'rgba(0,0,0,0.46)', borderWidth: 1, borderColor: 'rgba(255,255,255,0.22)' },
  topPillText: { color: COLORS.text, fontSize: 12, fontWeight: '900' },
  recordingTime: { minWidth: 68, textAlign: 'center', color: COLORS.text, fontSize: 15, fontWeight: '900', paddingHorizontal: 12, paddingVertical: 7, borderRadius: 17, backgroundColor: 'rgba(255,59,48,0.78)' },
  roundButton: { minWidth: 42, height: 42, borderRadius: 21, paddingHorizontal: 4, alignItems: 'center', justifyContent: 'center', backgroundColor: 'rgba(0,0,0,0.25)', borderWidth: 0, opacity: 0.65 },
  roundButtonActive: { backgroundColor: 'rgba(255,209,102,0.18)', opacity: 0.88 },
  roundButtonText: { color: COLORS.text, fontSize: 14, fontWeight: '800' },
  noBorderButton: { backgroundColor: 'transparent', borderWidth: 0, minWidth: 42 },
  pip: { position: 'absolute', zIndex: 18, overflow: 'hidden', borderRadius: 16, borderWidth: 2, borderColor: 'rgba(255,255,255,0.8)', backgroundColor: '#000' },
  pipLabel: { position: 'absolute', left: 6, bottom: 5, color: COLORS.text, fontSize: 10, fontWeight: '800', textShadowColor: '#000', textShadowRadius: 3 },
  pipTouchLayer: { position: 'absolute', top: 0, right: 0, bottom: 0, left: 0, zIndex: 2 },
  pipPlaceholder: { flex: 1, backgroundColor: 'rgba(10,10,10,0.92)', alignItems: 'center', justifyContent: 'center', paddingHorizontal: 10 },
  pipPlaceholderTitle: { color: COLORS.text, fontSize: 13, fontWeight: '900', marginBottom: 5, textAlign: 'center' },
  pipPlaceholderText: { color: COLORS.muted, fontSize: 11, fontWeight: '800', lineHeight: 15, textAlign: 'center' },
  zoomBarContainer: { position: 'absolute', left: 0, right: 0, bottom: 180, alignItems: 'center', zIndex: 25 },
  zoomBarShell: { width: ZOOM_BAR_WIDTH, height: 38, backgroundColor: 'rgba(0,0,0,0.22)', borderRadius: 19, borderWidth: 1, borderColor: 'rgba(255,255,255,0.1)', justifyContent: 'center', alignItems: 'center', overflow: 'hidden' },
  optionsRow: { flexDirection: 'row', alignItems: 'center', width: '100%', justifyContent: 'space-evenly' },
  optionItem: { height: '100%', paddingHorizontal: 8, justifyContent: 'center', alignItems: 'center' },
  optionText: { color: 'rgba(255,255,255,0.5)', fontSize: 12, fontWeight: '900' },
  activeText: { color: COLORS.accent },
  rulerContainer: { width: '100%', height: '100%', alignItems: 'center', justifyContent: 'center' },
  rulerStrip: { position: 'absolute', flexDirection: 'row', alignItems: 'flex-end', height: '100%', paddingBottom: 7 },
  markerGroup: { alignItems: 'center' },
  tick: { width: 1.5, height: 7, backgroundColor: 'rgba(255,255,255,0.3)', borderRadius: 1 },
  tickHalf: { height: 10, backgroundColor: 'rgba(255,255,255,0.5)' },
  tickMajor: { height: 15, backgroundColor: '#fff', width: 2 },
  tickLabel: { position: 'absolute', top: -13, color: 'rgba(255,255,255,0.6)', fontSize: 8, fontWeight: '800' },
  centerPointer: { position: 'absolute', width: 2.5, height: 22, backgroundColor: COLORS.accent, borderRadius: 2, zIndex: 3 },
  valueFloat: { position: 'absolute', right: 12, backgroundColor: 'rgba(0,0,0,0.28)', paddingHorizontal: 6, borderRadius: 10 },
  floatingValue: { color: COLORS.accent, fontSize: 13, fontWeight: '900' },
  toast: { position: 'absolute', left: 24, right: 24, bottom: 230, zIndex: 40, alignItems: 'center' },
  toastText: { overflow: 'hidden', color: COLORS.text, fontSize: 13, paddingHorizontal: 14, paddingVertical: 8, borderRadius: 18, backgroundColor: 'rgba(0,0,0,0.65)' },
  mediaJobIndicator: { position: 'absolute', left: 18, right: 18, top: TOP_BAR_OFFSET + 56, zIndex: 39, paddingHorizontal: 12, paddingVertical: 9, borderRadius: 8, backgroundColor: 'rgba(0,0,0,0.68)', borderWidth: 1, borderColor: 'rgba(255,255,255,0.14)' },
  mediaJobHeader: { flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between', gap: 12, marginBottom: 7 },
  mediaJobTitle: { flex: 1, color: COLORS.text, fontSize: 12, fontWeight: '900' },
  mediaJobStatus: { color: COLORS.accent, fontSize: 12, fontWeight: '900' },
  mediaJobTrack: { height: 3, borderRadius: 2, overflow: 'hidden', backgroundColor: 'rgba(255,255,255,0.18)' },
  mediaJobProgress: { height: '100%', borderRadius: 2, backgroundColor: COLORS.accent },
  bottomControls: { position: 'absolute', left: 0, right: 0, bottom: 0, zIndex: 26, paddingHorizontal: 22, paddingTop: 10, paddingBottom: 22, backgroundColor: 'transparent' },
  modeRow: { height: 34, flexDirection: 'row', alignItems: 'center', justifyContent: 'center', gap: 34 },
  modeText: { color: COLORS.muted, fontSize: 14, fontWeight: '700' },
  modeTextActive: { color: COLORS.accent },
  modeTextDisabled: { color: 'rgba(255,255,255,0.2)' },
  actionRow: { flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between', minHeight: 82 },
  thumbnailButton: { width: 52, height: 52, borderRadius: 12, backgroundColor: '#1f1f1f', borderWidth: 1, borderColor: COLORS.line, overflow: 'hidden', alignItems: 'center', justifyContent: 'center' },
  thumbnailImage: { width: '100%', height: '100%' },
  thumbnailText: { color: COLORS.text, fontSize: 12, fontWeight: '800' },
  shutter: { width: 74, height: 74, borderRadius: 37, borderWidth: 5, borderColor: '#fff', alignItems: 'center', justifyContent: 'center' },
  shutterRecording: { borderColor: COLORS.red },
  shutterInner: { width: 56, height: 56, borderRadius: 28, backgroundColor: '#fff' },
  shutterInnerRecording: { width: 28, height: 28, borderRadius: 7, backgroundColor: COLORS.red },
  viewModeRow: { height: 46, flexDirection: 'row', alignItems: 'center', justifyContent: 'center', gap: 14 },
  viewModeButton: { minWidth: 116, minHeight: 46, alignItems: 'center', justifyContent: 'center', paddingHorizontal: 10 },
  viewModeText: { color: COLORS.muted, fontSize: 13, fontWeight: '700' },
  viewModeTextActive: { color: COLORS.text },
  viewModeTextDisabled: { color: 'rgba(255,255,255,0.2)' },
  transitionOverlay: { backgroundColor: 'rgba(20,20,20,0.82)', alignItems: 'center', justifyContent: 'center', zIndex: 10 },
  transitionLogo: { paddingHorizontal: 32, paddingVertical: 16, borderRadius: 16, backgroundColor: 'rgba(255,255,255,0.03)', borderWidth: 1, borderColor: 'rgba(255,255,255,0.08)' },
  transitionLogoText: { color: COLORS.text, fontSize: 32, fontWeight: '900', letterSpacing: 4, textTransform: 'uppercase', opacity: 0.9 },
  compositionOverlay: { position: 'absolute', left: 0, right: 0, top: 0, bottom: 0, zIndex: 11, borderWidth: 1, borderColor: 'rgba(255,255,255,0.45)' },
  compositionOverlayStrong: { borderColor: 'rgba(255,209,102,0.86)', backgroundColor: 'rgba(0,0,0,0.08)' },
  compositionOverlayRecording: { borderColor: 'rgba(255,255,255,0.35)', backgroundColor: 'transparent' },
  compositionLabel: { position: 'absolute', left: 8, top: 8, overflow: 'hidden', color: COLORS.text, fontSize: 11, fontWeight: '900', paddingHorizontal: 7, paddingVertical: 4, borderRadius: 8, backgroundColor: 'rgba(0,0,0,0.46)' },
  compositionLabelStrong: { color: COLORS.accent, backgroundColor: 'rgba(0,0,0,0.66)' },
  compositionCornerTopLeft: { position: 'absolute', left: 0, top: 0, width: 22, height: 22, borderLeftWidth: 3, borderTopWidth: 3, borderColor: COLORS.accent },
  compositionCornerTopRight: { position: 'absolute', right: 0, top: 0, width: 22, height: 22, borderRightWidth: 3, borderTopWidth: 3, borderColor: COLORS.accent },
  compositionCornerBottomLeft: { position: 'absolute', left: 0, bottom: 0, width: 22, height: 22, borderLeftWidth: 3, borderBottomWidth: 3, borderColor: COLORS.accent },
  compositionCornerBottomRight: { position: 'absolute', right: 0, bottom: 0, width: 22, height: 22, borderRightWidth: 3, borderBottomWidth: 3, borderColor: COLORS.accent },
  modalShade: { flex: 1, justifyContent: 'flex-end', backgroundColor: 'transparent' },
  settingsPanel: { maxHeight: '82%', padding: 18, borderTopLeftRadius: 24, borderTopRightRadius: 24, backgroundColor: '#151515' },
  settingsHeader: { flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between', marginBottom: 14 },
  settingsTitle: { color: COLORS.text, fontSize: 20, fontWeight: '900' },
  closeText: { color: COLORS.accent, fontSize: 15, fontWeight: '800' },
  settingsTabs: { flexDirection: 'row', gap: 8, marginBottom: 14, padding: 4, borderRadius: 12, backgroundColor: '#0f0f0f' },
  settingsTab: { flex: 1, height: 38, borderRadius: 8, alignItems: 'center', justifyContent: 'center' },
  settingsTabActive: { backgroundColor: '#2d2d2d' },
  settingsTabText: { color: COLORS.muted, fontSize: 13, fontWeight: '800' },
  settingsTabTextActive: { color: COLORS.text },
  aboutAppTitle: { color: COLORS.text, fontSize: 18, fontWeight: '900', marginBottom: 2 },
  aboutVersion: { color: COLORS.muted, fontSize: 11, marginBottom: 4 },
  legalLink: { flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between', paddingVertical: 12, borderBottomWidth: 1, borderBottomColor: 'rgba(255,255,255,0.06)' },
  legalLinkText: { color: COLORS.text, fontSize: 14, fontWeight: '700' },
  legalArrow: { color: COLORS.muted, fontSize: 18, fontWeight: '300' },
  legalContentText: { color: COLORS.muted, fontSize: 13, lineHeight: 22, padding: 4 },
  settingsSection: { marginBottom: 16, padding: 14, borderRadius: 18, backgroundColor: '#222' },
  sectionTitle: { color: COLORS.text, fontSize: 15, fontWeight: '900', marginBottom: 10 },
  chipWrap: { flexDirection: 'row', flexWrap: 'wrap', gap: 8 },
  chip: { paddingHorizontal: 12, paddingVertical: 8, borderRadius: 999, backgroundColor: '#111', borderWidth: 1, borderColor: COLORS.line },
  chipActive: { borderColor: COLORS.accent, backgroundColor: 'rgba(255,209,102,0.18)' },
  chipDisabled: { opacity: 0.42 },
  chipText: { color: COLORS.muted, fontSize: 12, fontWeight: '700' },
  chipTextActive: { color: COLORS.text },
  settingLine: { color: COLORS.muted, fontSize: 12, lineHeight: 22 },
  focusBox: { position: 'absolute', width: 72, height: 72, borderWidth: 2, borderColor: COLORS.accent, borderRadius: 4 },
  galleryRoot: { position: 'absolute', top: 0, left: 0, width: '100%', height: '100%', backgroundColor: '#000', zIndex: 50 },
  galleryCloseIcon: { position: 'absolute', left: 16, height: 38, justifyContent: 'center' },
  galleryCloseText: { color: COLORS.accent, fontSize: 13, fontWeight: '900' },
  galleryTopBar: { position: 'absolute', left: 0, right: 0, top: 0, zIndex: 5, paddingTop: TOP_BAR_OFFSET, paddingHorizontal: 16, paddingBottom: 12, flexDirection: 'row', alignItems: 'center', justifyContent: 'center', backgroundColor: 'transparent' },
  galleryTopButton: { minWidth: 58, height: 38, borderRadius: 8, alignItems: 'center', justifyContent: 'center' },
  galleryTopText: { color: COLORS.text, fontSize: 14, fontWeight: '800' },
  galleryCount: { color: COLORS.text, fontSize: 14, fontWeight: '900' },
  galleryPage: { flex: 1, alignItems: 'center', justifyContent: 'center', backgroundColor: '#000' },
  galleryLazyPage: { flex: 1, backgroundColor: '#000' },
  galleryImage: { width: '100%', height: '100%' },
  galleryAssetStrip: { position: 'absolute', left: 18, right: 18, bottom: 92, zIndex: 8, flexDirection: 'row', justifyContent: 'center', flexWrap: 'wrap', gap: 8 },
  galleryAssetChip: { minHeight: 34, minWidth: 56, borderRadius: 8, paddingHorizontal: 10, alignItems: 'center', justifyContent: 'center', backgroundColor: 'rgba(0,0,0,0.62)', borderWidth: 1, borderColor: 'rgba(255,255,255,0.16)' },
  galleryAssetChipActive: { borderColor: COLORS.accent, backgroundColor: 'rgba(255,209,102,0.18)' },
  galleryAssetChipText: { color: COLORS.muted, fontSize: 12, fontWeight: '900' },
  galleryAssetChipTextActive: { color: COLORS.text },
  galleryJobBanner: { position: 'absolute', left: 18, right: 18, bottom: 142, zIndex: 8, paddingHorizontal: 12, paddingVertical: 10, borderRadius: 8, backgroundColor: 'rgba(255,59,48,0.16)', borderWidth: 1, borderColor: 'rgba(255,138,130,0.45)' },
  galleryJobBannerTitle: { color: '#ffb0aa', fontSize: 12, fontWeight: '900', marginBottom: 3 },
  galleryJobBannerText: { color: 'rgba(255,255,255,0.78)', fontSize: 11, lineHeight: 16 },
  galleryJobRetryButton: { alignSelf: 'center', marginTop: 10, minWidth: 72, height: 34, borderRadius: 8, alignItems: 'center', justifyContent: 'center', backgroundColor: 'rgba(255,255,255,0.16)' },
  galleryJobRetryText: { color: COLORS.text, fontSize: 12, fontWeight: '900' },
  zoomablePhoto: { width: '100%', height: '100%', alignItems: 'center', justifyContent: 'center', overflow: 'hidden' },
  zoomableImageFrame: { alignItems: 'center', justifyContent: 'center' },
  zoomResetButton: { position: 'absolute', right: 18, top: TOP_BAR_OFFSET + 42, minWidth: 52, height: 34, borderRadius: 8, alignItems: 'center', justifyContent: 'center', backgroundColor: 'rgba(255,255,255,0.18)' },
  zoomResetText: { color: COLORS.text, fontSize: 12, fontWeight: '900' },
  inlineVideoPlayer: { width: '100%', height: '100%', backgroundColor: '#000' },
  galleryEmpty: { flex: 1, alignItems: 'center', justifyContent: 'center' },
  galleryEmptyText: { color: COLORS.muted, fontSize: 14, fontWeight: '700' },
  mediaPreviewFallback: { minWidth: 210, minHeight: 180, borderRadius: 8, alignItems: 'center', justifyContent: 'center', paddingHorizontal: 28, backgroundColor: 'rgba(255,255,255,0.08)' },
  videoPreview: { alignItems: 'center', justifyContent: 'center', paddingHorizontal: 28 },
  videoPreviewIcon: { color: COLORS.text, fontSize: 54, fontWeight: '900', marginBottom: 12 },
  videoPreviewTitle: { color: COLORS.text, fontSize: 22, fontWeight: '900', marginBottom: 8 },
  videoPreviewText: { color: COLORS.muted, fontSize: 16, fontWeight: '800', marginBottom: 10 },
  videoPreviewHint: { color: COLORS.muted, fontSize: 12, lineHeight: 18, textAlign: 'center' },
  galleryBottomBar: { position: 'absolute', left: 0, right: 0, bottom: 0, zIndex: 5, paddingHorizontal: 18, paddingTop: 12, paddingBottom: 26, flexDirection: 'row', gap: 10, justifyContent: 'space-between', backgroundColor: 'transparent' },
  galleryBottomButton: { flex: 1, height: 42, borderRadius: 8, alignItems: 'center', justifyContent: 'center', backgroundColor: 'rgba(255,255,255,0.12)' },
  galleryDeleteButton: { backgroundColor: 'rgba(255,59,48,0.18)' },
  galleryBottomText: { color: COLORS.text, fontSize: 13, fontWeight: '900' },
  galleryDeleteText: { color: '#ff8a82' },
  mediaDetails: { position: 'absolute', left: 16, right: 16, bottom: 92, zIndex: 6, padding: 14, borderRadius: 8, backgroundColor: 'rgba(0,0,0,0.78)', borderWidth: 1, borderColor: COLORS.line },
  mediaDetailsTitle: { color: COLORS.text, fontSize: 15, fontWeight: '900', marginBottom: 8 },
  mediaDetailsText: { color: COLORS.muted, fontSize: 12, lineHeight: 20 },
  mediaDetailsPath: { color: 'rgba(255,255,255,0.48)', fontSize: 11, lineHeight: 16, marginTop: 6 },
});
